version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=eventsApp
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eventsApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
