# Generated by Django 4.1.13 on 2024-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('poster', models.ImageField(upload_to='images/')),
                ('open_air', models.BooleanField(default=False)),
            ],
        ),
    ]
