apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: django-app
  labels:
    app: postgres
data:
  POSTGRES_DB: eventsApp
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
